Repository ash-hat/H3MP, pull requests merged in 2020-10, with the labels that each got.

#3 Replace Primitive Hands with Index Controllers
  src/H3MP/Configs/ClientPuppetConfig.cs
  src/H3MP/Configs/ClientPuppetLimbConfig.cs
  src/H3MP/Peers/Puppet.cs
Labels: client, enhancement

#5 Automate Build Process
  .gitignore
  README.md
  scripts/get_discord_gamesdk.sh
  scripts/link_builds.bat
  scripts/link_game.bat
  src/H3MP.Networking/H3MP.Networking.csproj
  src/H3MP/H3MP.csproj
Labels: documentation

#6 Add Version Specification
  README.md
  docs/README.md
  docs/building.md
  docs/version.md
Labels: documentation

#7 Add changelog panel to the main menu
  src/H3MP/H3MP.csproj
  src/H3MP/Plugin.cs
  src/H3MP/Utils/ChangelogPanel.cs
  ui/mainmenu3-panel.txt
Labels: enhancement

#8 Add collision to the panel
  src/H3MP/Utils/ChangelogPanel.cs
Labels: bug
